chmod u+x main.sh
chmod u+x init.sh
chmod u+x calculate.sh
chmod u+x analyse.sh
chmod u+x final.sh
chmod u+x cutter.sh
chmod u+x genetic.sh
chmod u+x mkinput.sh
chmod u+x mkmodel.sh
chmod u+x demoni.sh
chmod u+x outputbest.sh
chmod u+x real.sh